# Site settings
title: A Policymaker’s Guide to Improving School Leadership
email:
description: > # this means to ignore newlines until "baseurl:"
  Principals play a critical role in supporting teachers and raising student achievement. Yet too little attention has been paid to what makes a great principal and how to get more of them in the schools that need them most. To help develop more coherent strategies for strengthening states’ principal policies, the Center on Reinventing Public Education and the Thomas B. Fordham Institute have built an online School Leadership Policy Toolkit for advocacy leaders and policymakers.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: CRPE_UW
github_username:

# Build settings
markdown: kramdown
